"""init

Revision ID: 9a146a2ad25b
Revises: 8cf663eb5543
Create Date: 2026-06-15 02:11:41.600939

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a146a2ad25b'
down_revision = '8cf663eb5543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('week', sa.Enum('WEEK_1', 'WEEK_2', name='weekenum'), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course', sa.Column('initial_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_course_initial_id'), 'course', ['initial_id'], unique=True)
    # Ensure there are no NULLs before making the column NOT NULL
    op.execute("UPDATE \"file\" SET file_path = '' WHERE file_path IS NULL")
    op.alter_column('file', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('file', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.alter_column('file', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_course_initial_id'), table_name='course')
    op.drop_column('course', 'initial_id')
    op.drop_table('lesson')
    # ### end Alembic commands ###
